import type { Metadata } from "next";
import { Bebas_Neue, Playfair_Display, Space_Mono } from "next/font/google"
import { ThemeProvider } from "@/app/contexts/ThemeProvider";
import "@/app/globals.css";

const bebasNeue = Bebas_Neue({
  variable: "--font-bebas-neue",
  subsets: ["latin"],
  weight: "400",
  display: "swap"
});

const playfairDisplay = Playfair_Display({
  variable: "--font-playfair-display",
  subsets: ["latin"],
  weight: ["400", "700"],
  style: ["normal", "italic"],
  display: "swap"
});

const spaceMono = Space_Mono({
  variable: "--font-space-mono",
  weight: ["400", "700"],
  style: ["normal", "italic"],
  subsets: ["latin"],
  display: "swap"
})

export const metadata: Metadata = {
  title: "Portfolio",
  description: "Portfolio website generated by Create-Next-App.",
};

export default function RootLayout({ children }: Readonly<{children: React.ReactNode;}>) {
  const fontVariables = `${bebasNeue.variable} ${playfairDisplay.variable} ${spaceMono.variable}`
  return (
    <html lang="en" data-theme="dark">
      <body className={fontVariables}>
        <ThemeProvider>
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
